# Generated by Django 6.0.2 on 2026-02-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_lat_restaurant_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=13, null=True),
        ),
    ]
