# Generated by Django 6.0.2 on 2026-02-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='break_time',
            field=models.CharField(blank=True, help_text='예: 15:00~17:00', max_length=100, null=True),
        ),
    ]
