# Generated by Django 6.0.2 on 2026-02-25 08:12

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_alter_ownerprofile_options_customerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
            ],
            options={
                'verbose_name': 'Customer User',
                'verbose_name_plural': 'Customer Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OwnerUser',
            fields=[
            ],
            options={
                'verbose_name': 'Owner User',
                'verbose_name_plural': 'Owner Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('OWNER', 'Owner')], db_index=True, default='CUSTOMER', max_length=20),
        ),
    ]
