version: 0.0
os: linux
file_exists_behavior: OVERWRITE

files:
  - source: /
    destination: /home/ec2-user/localeats
    overwrite: yes

permissions:
  - object: /home/ec2-user/localeats
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory

  - object: /home/ec2-user/localeats/scripts
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 600
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 120
      runas: root