# Generated by Django 5.2.12 on 2026-03-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_remove_favorite_unique_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
