# Generated by Django 6.0.2 on 2026-03-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0005_alter_favorite_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
