# Generated by Django 6.0.2 on 2026-02-24 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='photo',
            new_name='image',
        ),
    ]
