# Generated by Django 5.2.12 on 2026-03-04 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_alter_category_id_alter_menuitem_id_and_more'),
        ('reviews', '0005_reviewreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(db_index=True, default=5),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('restaurant', 'author')},
        ),
    ]
