"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import environ

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ['127.0.0.1', 'localhost']),
    CSRF_TRUSTED_ORIGINS=(list, []),
)

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])
SITE_URL = env('SITE_URL', default='')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local Apps
    'core',
    'users',
    'restaurants',
    'reviews',
    'favorites',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.user_flags',
                'core.context_processors.notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# .env에 DB_ENGINE=django.db.backends.mysql 설정 시 MySQL 사용
# 미설정 시 SQLite (개발용) 사용

_db_engine = env('DB_ENGINE', default='django.db.backends.sqlite3')

if _db_engine == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # 프록시 VIP를 통한 default(write) / readonly(read) 이중 DB 구성
    # 실제 DB IP 대신 프록시 VIP로 접속하며, 포트로 write/read를 구분
    DATABASES = {
        'default': {
            'ENGINE':   _db_engine,
            'NAME':     env('DB_NAME'),
            'USER':     env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST':     env('DB_HOST', default='192.168.1.177'),   # 프록시 VIP
            'PORT':     env('DB_PORT', default='3306'),             # write 포트
            'OPTIONS': {
                'connect_timeout': 10,
            },
        },
        'readonly': {
            'ENGINE':   _db_engine,
            'NAME':     env('DB_NAME'),
            'USER':     env('DB_READONLY_USER',     default=env('DB_USER')),
            'PASSWORD': env('DB_READONLY_PASSWORD', default=env('DB_PASSWORD')),
            'HOST':     env('DB_HOST', default='192.168.1.177'),   # 프록시 VIP (동일)
            'PORT':     env('DB_READONLY_PORT', default='3307'),    # read 포트
            'OPTIONS': {
                'connect_timeout': 10,
            },
        },
    }

# Router 등록: MySQL 환경에서 read 쿼리를 'readonly' DB로 분기
DATABASE_ROUTERS = ['config.db_router.ReadWriteRouter'] if _db_engine != 'django.db.backends.sqlite3' else []


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
# 개발: 로컬 media 폴더 / 프로덕션: EFS 마운트 경로
MEDIA_ROOT = env('MEDIA_ROOT', default=str(BASE_DIR / 'media'))

# ── 이메일 ───────────────────────────────────────────────
# DEBUG=True → 터미널 출력 / False → 실제 Gmail 발송
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND   = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST      = 'smtp.gmail.com'
    EMAIL_PORT      = 587
    EMAIL_USE_TLS   = True
    EMAIL_HOST_USER     = env('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
    DEFAULT_FROM_EMAIL  = EMAIL_HOST_USER

SITE_URL = env('SITE_URL', default='http://127.0.0.1:8000')

# ── 프로덕션 HTTPS / ALB 보안 설정 ───────────────────────────
# ALB가 SSL을 끊고 HTTP로 EC2에 전달하므로 X-Forwarded-Proto 헤더로 판단
if not DEBUG:
    SECURE_PROXY_SSL_HEADER  = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE    = True   # 쿠키를 HTTPS 전용으로
    CSRF_COOKIE_SECURE       = True   # CSRF 토큰을 HTTPS 전용으로
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # ALB 도메인 또는 실제 서비스 도메인을 CSRF 허용 출처로 등록
    CSRF_TRUSTED_ORIGINS     = env.list('CSRF_TRUSTED_ORIGINS', default=[])

# ── 외부 API 키 ──────────────────────────────────────────
NAVER_CLIENT_ID     = env('NAVER_CLIENT_ID', default='')
NAVER_CLIENT_SECRET = env('NAVER_CLIENT_SECRET', default='')
KAKAO_REST_API_KEY  = env('KAKAO_REST_API_KEY', default='')